import NeuralNetworkProofs
open UniversalApproximation.Cybenko UniversalApproximation.Leshno
open UniversalApproximation.MikulincerReichman UniversalApproximation.Sartor
  UniversalApproximation.Runje
#print axioms universal_approximation
#print axioms universal_approximation_eps
#print axioms leshno_dense_iff
#print axioms monotone_interpolation
#print axioms monotone_approximation
#print axioms saturating_interpolation
#print axioms nonpos_weight_universal
#print axioms partial_monotone_approximation
#print axioms PartMonoNet.monotone_snd
