import NeuralNetworkProofs
open UniversalApproximation.Cybenko UniversalApproximation.Leshno
#print axioms universal_approximation
#print axioms universal_approximation_eps
#print axioms leshno_dense_iff
